# Generated by Django 4.1.3 on 2022-12-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Published Video',
                'verbose_name_plural': 'Published Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
