# Generated by Django 4.1.3 on 2022-12-23 10:28

from django.db import migrations, models
import playlists.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_name_video_title_video_publish_timestamp_and_more'),
        ('playlists', '0004_alter_playlist_videos_playlistrelated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='related',
            field=models.ManyToManyField(blank=True, limit_choices_to=playlists.models.pr_limit_choices_to, related_name='related', to='playlists.playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlist_item', to='videos.video'),
        ),
    ]
