# Generated by Django 4.1.3 on 2022-12-23 10:45

from django.db import migrations, models
import playlists.models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_remove_playlistrelated_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='related',
            field=models.ManyToManyField(blank=True, limit_choices_to=playlists.models.pr_limit_choices_to, through='playlists.PlaylistRelated', to='playlists.playlist'),
        ),
    ]
