# Generated by Django 4.1.3 on 2022-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_name_video_title_video_publish_timestamp_and_more'),
        ('playlists', '0010_remove_playlist_related_playlist_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlist_video', to='videos.video'),
        ),
    ]
